[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"

# https://github.com/esp-rs/espflash
runner = "espflash flash --monitor"
#runner = "espflash flash --monitor --bootloader kukkuu/build/bootloader/bootloader.bin"

rustflags = [
  # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
  "--cfg",  "espidf_time64"
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s3"
ESP_IDF_VERSION = "v5.4.0"
