name: Run test build with esp-idf-rust image from DockerHub

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use stable Rust
      run: rustup default stable

    - name: Install espup
      run: cargo install espup

    - name: Build
      run: cargo +esp build --release
    
    - name: Archive binaries
      run: |
        mkdir binaries
        cp build/*.bin build/bootloader/*.bin build/partition_table/*.bin support/esptool/* binaries/
    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: binaries
