name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.7
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo +esp build --release --features esp-idf

      - name: Setup Rust for tests
        uses: dtolnay/rust-toolchain@stable

      - name: Run unit tests
        run: cargo test --lib --features test-utils --target x86_64-unknown-linux-gnu

      - name: Run integration tests
        run: cargo test --test unit_tests --features test-utils --target x86_64-unknown-linux-gnu

      - name: Check formatting
        run: cargo fmt --all -- --check --color always

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

      - name: Archive artifact
        uses: actions/upload-artifact@v7
        with:
          name: binaries
          path: |
            target/xtensa-esp32s3-espidf/release/mainichikatarenshu
            target/xtensa-esp32s3-espidf/release/bootloader.bin
            target/xtensa-esp32s3-espidf/release/partitions.bin